[screensaver]
activate.command = "xscreensaver-command -activate"
activate.description = "Activate the screensaver."

deactivate.command = "xscreensaver-command -deactivate"
deactivate.description = "Deactivate the screensaver."

[system]
reboot.command = "reboot"
reboot.description = "Execute an reboot."
