version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "%(levelname)s [%(asctime)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  access:
    format: "%(levelname)s [%(asctime)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  access_console:
    class: logging.StreamHandler
    level: INFO
    formatter: access
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: false
  uvicorn.access:
    level: INFO
    handlers: [access_console]
    propagate: false

root:
  level: INFO
  handlers: [console]
